language: node_js
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token:
    secure: pAnaUenr/TNux0rH0KMjIJoZ5usI4sFUq8zgi8DQMXjInntT0aGAtoARmN9EmN/ml7hN4tWMOv4etSQ/HCaOlZaip5hLdYcPmta/DNdvrCGyQvZgd7m4Cn4rp4XFOwikQSCDXBt9bNcfPqW0qHu0SlogG70BCHCwthSDRWm+i17pcvpG/YJB1ydxt6+M7pV2psQ2eO+BF4sU9JRSpE4WxbefKhR9MOmh3z0836lbSEb2DLmv+y59VQHY1q1A+qvMOqiG5ijs50yeX5NFW3vbaPI3TfrRlQwsmUs0sRHg9uIM+Xkgd54CK4JgFWSoZyGhIB832Mth9CyjtJ+3Inj06pmprhbnV66bt6JKdiew3H7aUzKunDX96j+oRchk8d2qhbhWbd9f3XjUNfvSOXESx8IkVNOf6MAm56V1qs7c/12CRyipOmg6I+rORZWIbhW+XZBoUtEHfaPk2VfzFdmwqzCCa+YvQgMs6UqcvVXIL0fCLWoGf4raeiHMyDe5kYrgzh5/msYAffX+ZkxH7qvf32WqErCbI5lQ6IVyi/yhfXVRcdbTEnYGGXUKNKKX3u45VV8iZn4pktRxRmu+TPX4BBRznbaocZpXdHAgCsLng901XjYBM3hwxiY+EzZRHC9lnnUUwjh+drpxLWe7J3pCRn87D81OdWuVuAZtzOeIeMc=
  keep-history: true
  on:
    branch: master