language: node_js
node_js:
- '7'
install:
- npm install
script:
- npm run build
deploy:
  provider: surge
  domain: monumentum.surge.sh
  project: ./dist
  on:
    branch: master
env:
  global:
    secure: O8AgXu3+QBEjvf6Z5aQf0DIc6Ot2FIllWB8/5QihFUM2xfFY7Axp/FaljEDOJSfrVLCmA0Sj67ZS2Z7DIO33eWIlA0ss0A+WE/TkFU8OGMGMdmx9Z1SCbyX5t2brUj1AuQmK7LYtzGmN1oCdzUrJ8Kb294yxa9uCBKXHdhF9qtaJVxsa1UORnthrWXaKpowS3TvxF+j7EpnpTkJxnzyzBL48xG38lmZ1Du+uL/E3nxlndFTYx690jf+gwA9lvascDIX1P9soFcOUPFfwvbt1ILLiMYZokoqDy7cVQdnqR/h/URkSSqhYmc/zSzX9oUhkCK+kWnY2/kvNVISnfjaCID4CSGEyijeyiOUTsF0KOULYdrcHVzSnvL6kEorpP/cVHy2jNAKCuWNsEAfiuEFptW6/smK50R2EMIkFpWloGG8JnNhVb0L3ojwBDzmdTqN99OZVn18vZuXKDJKhIu/JS6ObZ9+R27MnoitQ/9BJkpmIPYIdg0tdnQJYBKltksXA4vipZNhn/d+ze3JBGJ2zqyrgLdSxdvdBX807HAvwcP067T1qU5qEvqUG/I5lfxU4n2WH0AwefC4ajyCG9hfHb0P7J6edWxsvzPcoc21WOkPZ7TQBcc0vYSvKo2GFgTEwUSBmIW/L6X97ZQIFm1dC2rpTtd6dWGuAoCtHHxgkm3g=
